# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-29 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default='456456-fghgfhgf-456456456-fghg', max_length=255),
            preserve_default=False,
        ),
    ]
