# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-29 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_token_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('b1d65df5-49d1-49bb-8362-b4c354c5bbca'), max_length=255),
        ),
    ]
